# Generated by Django 5.2.6 on 2025-09-10 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время синхронизации"
                    ),
                ),
                (
                    "added_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество новых добавленных мероприятий",
                    ),
                ),
                (
                    "updated_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество обновленных мероприятий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат синхронизации",
                "verbose_name_plural": "Результаты синхронизаций",
            },
        ),
    ]
