# Generated by Django 5.2.6 on 2025-09-10 17:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Площадка",
                "verbose_name_plural": "Площадки",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "event_time",
                    models.DateTimeField(
                        verbose_name="Дата и время проведения мероприятия"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(verbose_name="Крайний срок регистрации"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыт"), ("closed", "Закрыт")],
                        verbose_name="Текущий статус",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        verbose_name="Дата и время изменения мероприятия"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
