# Generated by Django 5.2.6 on 2025-09-12 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="title",
            new_name="name",
        ),
    ]
