# Generated by Django 5.2.6 on 2025-09-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_title_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.DateTimeField(
                db_index=True, verbose_name="Дата и время проведения мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                db_index=True, verbose_name="Крайний срок регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("open", "Открыт"), ("closed", "Закрыт")],
                db_index=True,
                verbose_name="Текущий статус",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
