# Generated by Django 5.2.6 on 2025-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_event_time_alter_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
    ]
